# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170503_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='repository.HostGroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='host_to_remote_users',
            field=models.ManyToManyField(blank=True, to='repository.HostToRemoteUser'),
        ),
    ]
